import Head from 'next/head';
import {Fragment} from 'react';
import LayoutUser from '../components/layouts/LayoutUser/LayoutUser';
import BannerHome from '@/components/pages/user/home/BannerHome/BannerHome';
import CategoryHome from '@/components/pages/user/home/CategoryHome/CategoryHome';
import BannerIntroduce from '@/components/pages/user/home/BannerIntroduce/BannerIntroduce';
import FeaturedProducts from '@/components/pages/user/home/FeaturedProducts/FeaturedProducts';
import AboutHome from '@/components/pages/user/home/AboutHome/AboutHome';
import HeroSection from '@/components/pages/user/home/HeroSection/HeroSection';
import HeroSlider from '@/components/pages/user/home/HeroSlider/HeroSlider';

export default function Home() {
	return (
		<Fragment>
			<Head>
				<title>Trang chủ</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Fragment>
				<HeroSection />
				<CategoryHome />
				<AboutHome />
				<FeaturedProducts />
				<BannerIntroduce />
			</Fragment>
		</Fragment>
	);
}

Home.getLayout = function getLayout(page) {
	return <LayoutUser>{page}</LayoutUser>;
};
